---
title: "Ressources complémentaires - Chapitre 4"
author: "Rémi Anselme"
date: "`r Sys.time()`"
output:
  github_document:
    toc: yes
    toc_depth: 6
  html_document:
    toc: yes
    toc_depth: '6'
    df_print: paged
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
`%>%` <- magrittr::`%>%`

library(knitr)

library(dplyr)
library(ggplot2)
library(readr)
library(stringr)

source("Functions/functions_phoible.R") #Beaucoup de fonction inutiles pour ce projet, à nettoyer

# Figure and Table caption adapted from https://stackoverflow.com/questions/37116632/rmarkdown-html-number-figures: 
outputFormat = opts_knit$get("rmarkdown.pandoc.to"); # determine the output format of the document
if( is.null(outputFormat) ) outputFormat = ""; # probably not run within knittr
capTabNo = 1; capFigNo = 1; # figure and table caption numbering, for HTML do it manually
#Function to add the Table Number
capTab = function(x){
  if(outputFormat == 'github_document'){
    x = paste0("***Table ",capTabNo,".*** _",x,"_")
    capTabNo <<- capTabNo + 1
  }; x
}
#Function to add the Figure Number
capFig = function(x){
  if(outputFormat == 'github_document'){
    x = paste0("***Figure ",capFigNo,".*** _",x,"_")
    capFigNo <<- capFigNo + 1
  }; x
}
```

# Chapitre 4

## Préparation des données

Les données ont été préparés dans le fichier `data_processing.R` (*pas totalement mis au propre*). Nous avons récupéré des fichiers `.csv`. De cette préparation des données, nous obtenons systématiquement des données  en `.RData` prête à être importées sur R.

# Références

## Packages utilisés
```{r}
ins.pack <- installed.packages()[names(sessionInfo()$otherPkgs), "Version"] %>% 
  as.data.frame() %>% tibble::rownames_to_column()
names(ins.pack)[1] <- "Packages"
names(ins.pack)[2] <- "Version"

ins.pack %>% knitr::kable()
```

## Version de RStudio
```{r}
rstudioapi::versionInfo()
```